### ISSUE TITLE
Blaze Cakes Not Working

### ISSUE THREAD

**Issue by Fischer1000** [LopyLuna/Create-Flavored#104]
I was using DnD for a long time in my modpack, but not long ago I noticed, that when this mod is loaded, Blaze Cakes can't make Blaze Burners seething. With other methotds, such as Create: Diesel Generator's fuels they could enter seething, witch is wierd.

The mod version is 1.20.1-0.1b Early Dev Release
Minecraft version is 1.20.1
Create version is 0.5.1h (but it didn't work with other versions neither)

Thanks in advance for the fixes, I really don't want to remove DnD from my pack.

**Comment by LopyLuna** [comment]
known issue and been fixed for the next update
install "Load my F***ing tags" mod to fix the issue currently
