### ISSUE TITLE
game crash/mod conflict

### ISSUE THREAD

**Issue by superblast1** [LopyLuna/Create-Flavored#107]
whenever i try using this mod at the same as mystical agriculture the game crashes upon opening a world i found a similar thing mentioned in the mystical agriculture GitHub and they said it was an issue on the dreams and desires end 
https://github.com/BlakeBr0/MysticalAgriculture/issues/699

**Comment by LopyLuna** [comment]
already been fixed for next update

**Comment by superblast1** [comment]
> already been fixed for next update

do you know when that will be? 


ps: i love your mod

**Comment by LopyLuna** [comment]
![image](https://github.com/user-attachments/assets/39eaeaa8-6cd3-4e79-b014-56b519296cea)

Same concept basically

**Comment by superblast1** [comment]
i was asking because im trying to decide which one i should start my world without
