### ISSUE TITLE
add a config option to disable right clicking with planks on small cogwheels and turning them into large cogwheels

### ISSUE THREAD

**Issue by Flintley** [LopyLuna/Create-Flavored#109]
when holding a plank (for example an oak plank) and you right click on a small cogwheel it turns into a large cogwheel.
it would be better to have a world/global config option to disable this behavior because it is incompatible with create: encased (normally you change the cogwheel's material with this function) and a good idea in general.

**Comment by LopyLuna** [comment]
ill use buttons in the item application recipe
