### ISSUE TITLE
Giant Cogwheel teeth alignment (Model Issue)

### ISSUE THREAD

**Issue by nailuj9002** [LopyLuna/Create-Flavored#114]
The teeth of the giant cogwheel are aligned perfectly with the teeth of the large cogwheel And not in a way that makes sense
![image](https://github.com/user-attachments/assets/37bf116b-ae66-4150-ba85-09438d7d2a10)

**Comment by nailuj9002** [comment]
Also Just an opinion The furnace engine having a unique furnace flywheel with only one side output was better (the old model that had copper on it looked cooler)

**Comment by LopyLuna** [comment]
you should check out the diagonal large cogwheel connection :3
