### ISSUE TITLE
1.20.1 - Insane console spam trying to generate ocean stuff

### ISSUE THREAD

**Issue by Vipibolt** [LopyLuna/Create-Flavored#14]
There seems to be an issue in the most recent version of Create: Dreams & Desires something related to chunk generation. Not sure if this is something related to debug that was forgotten to be turned off or a genuine issue, but here's example of what is being thrown in the logs:
> [Worker-Main-31/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [-17, 9], pos: MutableBlockPos{x=-262, y=35, z=148}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_ocean]

Whatever this is, it's throwing it in the **thousands** in the console log, it does stop after it's done generating a new chunk. Hopefully something can be done about this since it's pretty bothersome. It is a beta build after all.

Running Forge 47.2.4
With mods:
> create-1.20.1-0.5.1.f
> Create-Dreams-n-Desires-1.20.1-0.2b.PREBETA

**Comment by LopyLuna** [comment]
https://discord.com/channels/1111311967454507032/1178017941648842783
https://discord.gg/8gHcjRAQrQ
