### ISSUE TITLE
[Feature request] Questions, QoL suggestions and mod compatibility changes. 

### ISSUE THREAD

**Issue by ffuentesm** [LopyLuna/Create-Flavored#15]
I love this mod, as it adds a lot of old features back to the game. Especially the chromatic compound, as some other mods still had compact to that "lost ingot"

I think it would be nice if there was a more comprehensive config; to allow certain features to be enabled. I enjoy the Create items that this adds, but I am not much of a fan of the stones, so would be nice if we could have an "on/off" on certain groups of features, such as [decorative blocks] [old feature] [new items] [casins]. 

Also, could the Bronze ingot have the standard forge:ingot/bronze tag instead of strong_bronze? For more mod compatibility. 

Also, "industrial iron", from what I see, it's just an extra step in making steel, and a strange way to get "double crafting yield". Could you make it so that normal iron can make steel?

And could you make a compat, so that 9 nuggets of experience craft into an ingot of experience, and 9 ingots of experience craft into a block of experience?

**Comment by LopyLuna** [comment]
1st - Bronze ingot is not the standard bronze you expect the bronze in this mod is known as "Red Brass / Gunmetal" its a Copper, Zinc, Tin Alloy it have a similar strength as steel but the normal known Traditional Bronze is a Copper & Tin Alloy & its weaker then steel hence thats why you see Strong Bronze & no Bronze Tags

2nd - ill consider the steel recipe but industrial iron version is cheaper & for the double crafting yield is a QoL Feature & been seeing people needing alot of iron hence the industrial iron duping plus its during the time when you have access to brass too & should help people out with andesite stuff after getting done with it & heading to the brass tier

3rd - I made Frozen XP for Looting(Planned), & Crafting Recipes another reason is that people when installing this mod on existing worlds dont get 9x more xp nugget then before if i go for a xp ingot to xp block conversion
