### ISSUE TITLE
[1.20.1] Doble ponder tooltip when Dream and Desires is installed

### ISSUE THREAD

**Issue by ffuentesm** [LopyLuna/Create-Flavored#16]
Create items have a duplicated tooltip description when the mod is installed.
Without the mod
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/44974827/46889b7b-877e-4e30-9041-0471c2c13302)
With the mod
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/44974827/b7edfdea-bef7-4689-b78d-2a58a0f32bf5)

**Comment by LopyLuna** [comment]
duped issue
fixed indev for next patch
