### ISSUE TITLE
 create_dd:striated_ores_ocean

### ISSUE THREAD

**Issue by Wheatley11** [LopyLuna/Create-Flavored#17]
![20231202160138](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/107456419/1ca4e1ee-0c56-4527-a8d6-0c7e396a8bef)
After I added the mod to the server, the server kept popping up such messages

[Worker-Main-13/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [76, -200], pos: MutableBlockPos{x=1219, y=3, z=-3185}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_ocean]

**Comment by Wheatley11** [comment]
Server version 1.20.1

**Comment by antonymous3lmao** [comment]
Having the same issue in 1.19.2

**Comment by LopyLuna** [comment]
Not an issue with my mod but Minecraft or Forge itself
https://www.curseforge.com/minecraft/mc-mods/detected-setblock-be-gone

**Comment by Wheatley11** [comment]
Thank you,But I found another problem
![Uploading 20231204104259.png…]()
![20231204104251](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/107456419/bb047e3c-e307-4eed-84e7-4f06f51daabf)
"Hold [W] to Ponder"
It turned into two

**Comment by Wheatley11** [comment]
Also in version 1.20.1

**Comment by LopyLuna** [comment]
that already fixed in dev i need to go fix a few other issues to update the mod
