### ISSUE TITLE
Items from Create and DnD are removed from Creative tab at random

### ISSUE THREAD

**Issue by Snooziepup** [LopyLuna/Create-Flavored#20]
When Create and DnD are installed together, items may dissapear from their respective creative tabs. Should note this issue also seems to exist with many other mods that use Create's codebase, with Steam n' Rails being the only one I could verify that doesn't.

**Comment by LopyLuna** [comment]
not an issue with DnD but with create instead

**Comment by BobBobson8** [comment]
> not an issue with DnD but with create instead

fuck, when  they gonna fix it

**Comment by LopyLuna** [comment]
no clue

**Comment by BobBobson8** [comment]
FUCK

**Comment by Snooziepup** [comment]
yeah ive been having the issue for like a month, how haven't they worked it out yet?????

**Comment by Snooziepup** [comment]
i asked about on Create's discord and they said the issue is the addon not handling tabs correctly, as apparently the tabs system was changed in 1.20
