### ISSUE TITLE
[Feature Request] Rubber Compatibility with Thermal Series

### ISSUE THREAD

**Issue by ffuentesm** [LopyLuna/Create-Flavored#21]
Could you add some forge tags to the rubber woods to make them compatible with Thermal rubber trees? 
Mainly the forge:rubberwood_log tag. 
Also the rubber item from thermal is also usable in Create DD rubber recipe. 

![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/44974827/1a4966c9-6464-4942-9f2f-4b602f5c5f71) 
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/44974827/830d4cdf-e9a2-4e4d-982f-e5d1e518b8a3)

**Comment by LopyLuna** [comment]
if i do this itll cause issues with other mods that haves DnDesire & Thermal Support

**Comment by ffuentesm** [comment]
What issues exactly? 
I tested things a bit by manually adding the tag to the blocks, and I haven't seen many issues.
The same goes for adding the forge:rubber and forge:raw_rubber to the items. 
Would be nice if Create_dd had built-in compact to Therma rubber and Latex fluids so they can be interchangeable.

**Comment by ffuentesm** [comment]
On a side note, could the Latex extraction process be with a basin and a press instead of a fluid drain? 
that way it feels as if we are trying to squeeze the sap out of the log.
