### ISSUE TITLE
[CONSISTENCY SUGGESTION] Processing Sail Consistency

### ISSUE THREAD

**Issue by everydayeldergod** [LopyLuna/Create-Flavored#22]
Version: All
This suggestion is to enhance parity between the original Create Mod fan mechanics and the Dreams and Desires equivalent. Currently, the Industrial Fan placed behind any of the specialty processing sails does not process items unless they are placed in the world. It should, for consistency and compactness, process items that are in depots and belts that move in front of the sail. This would be a huge help especially to make non-laggy quarry processing more efficient.

**Comment by DariusZeBaguette** [comment]
the fact that you need to drop the item is not a feature, but an issue with create that you cant make custom fans compatible with depots and belts, but in the next update, rubber depots n belts are gonna be added with cool features but most importantly industrial fan compat

**Comment by everydayeldergod** [comment]
while you're adding new rubber-based blocks, a connected-texture rubber block with a gray color sounds nice. maybe a compound bow with a rubber string as well?

**Comment by everydayeldergod** [comment]
what if those rubber conveyers had an adhesive option to transport items upward (or possibly even on the bottom)? it could be crafted with 8 belts and one slimeball? Or a throwable bouncy ball? sorry for all the suggestions, it just seems like rubber has so many possibilities.

**Comment by RechercheRaptor** [comment]
I was able to get the Haunting and Seething Sails to process base Create mod recipes with the items on depots, but I was wondering why none of the Dreams & Desires-specific recipes were working (all of my testing involved depots). Glad to know it wasn't just an issue on my end, and that the recipes do function otherwise!
