### ISSUE TITLE
Ornate Iron Glass Pane has flipped edges.

### ISSUE THREAD

**Issue by mikkolukas** [LopyLuna/Create-Flavored#24]
When placing Ornate Iron Glass Panes, the left and right edges seems flipped, as shown on the images.

4 column panes
![2023-12-29_02 16 21_cropped](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/1522239/875bf7d8-22da-4d98-b417-936ba33b780a)

3 column panes
![2023-12-29_02 16 26_cropped](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/1522239/571c4c1d-670c-40a0-9604-919832416773)

2 column panes
![2023-12-29_02 16 35_cropped](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/1522239/ff1639b1-921a-4120-867f-b38b8a8899ee)

It if course works as expected in single column panes:
![2023-12-29_02 16 38_cropped](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/1522239/6c3f15c5-306d-476b-8ada-e921b7bc18a9)

---

OS :: Windows 11
Java :: 17.0.8.1
Minecraft :: 1.20.1

Create :: 0.5.1f
Create: Dreams & Desires :: 0.2c.PREBETA

No other mods installed.

**Comment by LopyLuna** [comment]
will be moved to a different mod
