### ISSUE TITLE
[suggestion]Requests to enable various types of casings to be fitted to various types of shaft or gears.

### ISSUE THREAD

**Issue by Dawnwalker666** [LopyLuna/Create-Flavored#26]
The texture in this mod are fantastic! But it seems to be used only for decoration. So would it be possible to be able to slip in shaft or gears like the brass or andisite casings of the Create mod? I guess it would be prettier and more functional. 
After all, the recipe for this is expensive.

**Comment by LopyLuna** [comment]
its planned for the future but not now
