### ISSUE TITLE
Can't drain logs to get sap

### ISSUE THREAD

**Issue by RechercheRaptor** [LopyLuna/Create-Flavored#27]
I'm on Minecraft 1.19.2, Forge version 43.3.5, Create version 0.5.1.f, and Create: Dreams & Desires version 0.2.5b.PREBETA. Basically I can't get sap in survival mode. All that happens when I try right-clicking (or shift-right-clicking) the item drain with logs/wood/stripped versions is that I place the block on top, and get no sap in the item drain.

**Comment by LopyLuna** [comment]
you throw it onto is

**Comment by LopyLuna** [comment]
you throw onto it
