### ISSUE TITLE
Chunk Cascade Issue

### ISSUE THREAD

**Issue by SaltSouls** [LopyLuna/Create-Flavored#28]
The stuff with oceans is extremely unoptimized right now and is causing huge amounts of tick lag because it is causing chunk cascading. This should be fixed to help optimize the terrain gen aspect of this mod and prevent huge tick lag.
`[23:28:33] [Worker-Main-23/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [147, 35], pos: MutableBlockPos{x=2365, y=20, z=562}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_ocean]`

**Comment by LopyLuna** [comment]
minecraft/forge issue

https://www.curseforge.com/minecraft/mc-mods/detected-setblock-be-gone

**Comment by SaltSouls** [comment]
I wouldn't say that... I get huge amounts of lag when going into ocean biomes, and other mods that do terrain gen don't generate this issue. This is an issue with how your mod is handling terrain gen and it is causing massive amounts of cascading chunk generation. When I disable the mod, I no longer get a ton of lag around ocean biomes.

**Comment by LopyLuna** [comment]
Code is from create itself all I done is basically is copy and pasted the code
been trying to fix this issue for a bit and no luck (trying to not use any mixins)

plus I dont really ever get lag in the ocean biomes

**Comment by LopyLuna** [comment]
if you know how to fix the issue then be my guess and make a pull request
ill re-open this issue

**Comment by ItsLiterallyRen** [comment]
Hello, I a Moderator on a Create based server and we also have this issue which basically just crashes/timeouts the server after like a minute of being inside of chunks like these. It happens in certain ocean areas and also in savanna areas

[18:41:22] [Worker-Main-9/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [76, -395], pos: MutableBlockPos{x=1220, y=33, z=-6305}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_savanna]

Honestly have no idea why this does happen

**Comment by ascenstohe4vn** [comment]
[detectedSetBlockbeGone](https://www.curseforge.com/minecraft/mc-mods/detected-setblock-be-gone)

**Comment by SamuelMereau** [comment]
Hi, apologies for reopening this, I'm running a Forge server on Minecraft 1.19.2 and I am also seeing this warning being sent continuously in the server log, followed by heavy tick lag. Keen to see how this issue progresses. Many thanks

**Comment by LopyLuna** [comment]
[detectedSetBlockbeGone](https://www.curseforge.com/minecraft/mc-mods/detected-setblock-be-gone)

**Comment by SamuelMereau** [comment]
Thanks, sorry if I'm being oblivious but this seems like it disables the warning but would it resolve the core issue, if there are any? Please clarify
