### ISSUE TITLE
Crash on Start, Heavily Modded Forge

### ISSUE THREAD

**Issue by calin-cox** [LopyLuna/Create-Flavored#30]
[latest.log](https://github.com/LopyLuna/Create-Dreams-and-Desires/files/14367322/latest.log)
[crash-2024-02-21_19.47.14-fml.txt](https://github.com/LopyLuna/Create-Dreams-and-Desires/files/14367326/crash-2024-02-21_19.47.14-fml.txt)

![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/156495154/5462b240-bf24-4fb6-96b6-8a1fd3a0a1cf)

The computer is running Windows 10, and is up to date in all possible areas (drivers, java, windows). Personal pack, but I will happily share the modlist. Pack loads on several other computers without issue. Pack loads with Dreams and Desires disabled. I am unsure what causes this behaviour, and would love some help in addressing it.

Thank you.

**Comment by LopyLuna** [comment]
Outdated Version
