### ISSUE TITLE
Valkyrian Physics causes bug in Copycat Block in 1.18.2

### ISSUE THREAD

**Issue by KODU16** [LopyLuna/Create-Flavored#31]
Valkyrian Skies adds physics to blocks and it causes bug
when adding physics to a copycat block, it will drop a block it copies
for example when adding physics to a copycat block(right click with a diamond block), it will drop a diamond block after summoning a copycat block with physics
it causes severe item duplicate in survival mode

**Comment by LopyLuna** [comment]
copycat blocks will be removed and be moved to a different mod
