### ISSUE TITLE
Mechanical Press recipe conflict with Create: Deco

### ISSUE THREAD

**Issue by PenumbraStar** [LopyLuna/Create-Flavored#33]
Various conflicts with the sheets, such as Industrial Iron and Andesite Alloy Sheets, and ones added by Create: Deco.

**Comment by Lazzeruz** [comment]
I started a compatibility project for the create addons due to the same issue. Will add datapacks with recipes where I see them.

https://github.com/Lazzeruz/create_addon_compats

I'll update them soon enough.

**Comment by PaulRV0709** [comment]
> I started a compatibility project for the create addons due to the same issue. Will add datapacks with recipes where I see them.
> 
> https://github.com/Lazzeruz/create_addon_compats
> 
> I'll update them soon enough.

Would this become a mod or just a datapack?
