### ISSUE TITLE
Create creative TAB in empty

### ISSUE THREAD

**Issue by MaxTechnik3796** [LopyLuna/Create-Flavored#42]
When I play with this mod, my Create creative tab looks like this:
![Image02](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/144486710/2086f675-3306-4cfe-b0ec-b77d401ba3b5)

**Comment by Syndaryl** [comment]
This also extends to JEI - if the block isn't visible in Creative, it also isn't visible in JEI
