### ISSUE TITLE
Mod prevents JEI from showing sequenced assembly.

### ISSUE THREAD

**Issue by PaulRV0709** [LopyLuna/Create-Flavored#43]
When this mod is installed, JEI cannot show the sequenced assembly of anything, whether or not it is an item added by this mod.

I could see if there are any errors when I try to see the recipe if needed.

**Comment by LopyLuna** [comment]
this is consider invalid atm because no modlist, version, modloader, and screenshots

and this is likely due to a mod incompatibility as this is the first kind of issue ive seen
