### ISSUE TITLE
World Gen Config Option appears broken

### ISSUE THREAD

**Issue by TrickShow** [LopyLuna/Create-Flavored#45]
The config option to disable world gen is in the config file but appears to do absolutely nothing. Please fix this in many cases when making a mod pack not being able to disable the world generation when another mod is handling all world gen causes game-breaking world generation. 

V1.20.1

**Comment by LopyLuna** [comment]
make or use a datapack to disable them

also most is getting a rewrite

**Comment by LopyLuna** [comment]
mod* not most

**Comment by TrickShow** [comment]
Oh you are rewriting it for 1.20.1?
