### ISSUE TITLE
Detected setBlock in a far chunk 

### ISSUE THREAD

**Issue by DMNerd** [LopyLuna/Create-Flavored#49]
Detected setBlock in a far chunk [6, 81], pos: MutableBlockPos{x=96, y=12, z=1301}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_ocean]

Error being spammed on latest version on Neoforge

**Comment by LopyLuna** [comment]
will be fixed in rewrite of the mod
