### ISSUE TITLE
[Suggestion] Radiant panels and shadow panels rotate in different directions according to their coordinates

### ISSUE THREAD

**Issue by Xrisium** [LopyLuna/Create-Flavored#53]
All the radiant panels and shadow panels now rotate in the same direction and make it hard to put panels together (unless you put cogwheels among them, which is a waste of space). Making panels rotate in different directions according to their coordinates might help. For example, if x-coordinate plus z-coordinate equals a even number, the panel will rotate clockwise, and vice versa.
Sorry that I know little about Java and don't know if this is possible technically. If possible, hope you can add this feature in future versions, and thanks a lot!

**Comment by LopyLuna** [comment]
being move to a different mod
