### ISSUE TITLE
[Bug]Failed to load

### ISSUE THREAD

**Issue by TheYatsu** [LopyLuna/Create-Flavored#54]
(My English may be bad. sorry...!)
Minecraft version:1.19.2
Forge version:43.3.7(but I tried 43.3.13 before and it also had the same issue)
More system details:
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/145763413/0daec9fd-ee26-46c0-a168-d9ddbb94fc41)

--Summary--
After that issue was fixed, I tried version 1.19.2-0.2a.ALPHA.
But it failed again to load with same screen,
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/145763413/d69a69f9-5d3c-4055-87ec-42ad4cc410c6)
and the crash report said:
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/145763413/e927ea8d-f96b-4be7-b96e-6403c5d8913b)
PartialModel issue but it's Giant gear version...?
I suspected the mods' conflict,
**so I tried Create & Create: dndesires only. but it also crashed with end code 1.**
I'm not angry at it, rather I apologize my ignorance. Thank you for the fix of issue before!

**Comment by LopyLuna** [comment]
should be fixed now

**Comment by TheYatsu** [comment]
Thank you so much!!!
