### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by nul666lun** [LopyLuna/Create-Flavored#56]
![3](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/160829359/9e1b5c97-a6aa-44d1-9684-82c9f775f93b)
Why are these missing from the mod? i see nothing in any changelog... why is the image still posted? what is going on?

**Comment by LopyLuna** [comment]
mod is currently in a rewrite stage
i need to update the images later
