### ISSUE TITLE
Industrial Fan not working with Sails on Depot

### ISSUE THREAD

**Issue by lightningwolfblade** [LopyLuna/Create-Flavored#6]
All Sails don't work with the Industrial Fan while items are on the Depot or the Mechanical Belt. They only work while the item is against a block.

Working:
![2023-09-10_15 22 12](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/62543354/9fd28731-cbb3-483b-b000-a98eb2c46896)

Not Working:
![2023-09-10_15 22 37](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/62543354/755c0608-6328-4c23-b71d-510037e042b9)

**Comment by LopyLuna** [comment]
there is gonna be a depot/belt that is gonna support the fan & also obv the encased fan
