### ISSUE TITLE
Certain Blocks Are Unable To Be Uncrafted Back Into Original State

### ISSUE THREAD

**Issue by Knewest** [LopyLuna/Create-Flavored#60]
### Mod version:
`fabric-1.20.1-1.2.3`

### Issue:
Things that can be crafting into blocks for whatever reason cannot be reverted into 9 of the unblocked state. I believe this is unintentional as the recipes for them exist, but do not function. I am unsure of how many items have this issue, but I know tin and leather do.

### Images:
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/94736474/abd1d2a3-04c3-4b36-866e-e28dabe54bda)
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/94736474/7c152805-cd01-4cd4-a477-7bbebac24584)
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/94736474/b16b5f6a-69c6-4967-af17-c65204741881)

**Comment by LopyLuna** [comment]
Mod currently getting a rewrite and the following content that you listed will be removed from the main mod

**Comment by Knewest** [comment]
Right, so what are the existing servers with these blocks supposed to do? I've essentially been locked out of my resources due to the fact that I cannot 'decraft' the blocks into their original states.

**Comment by LopyLuna** [comment]
also id suggest downloading "load my f***ing tags" it may fix the issue

**Comment by Knewest** [comment]
LMFT unfortunately did not work (Yes, it was added to the server).
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/94736474/0b700665-bd3a-4be8-9a69-4960d77de95b)
