### ISSUE TITLE
Some Casing blocks do not properly have their respective item tag

### ISSUE THREAD

**Issue by Mickeon** [LopyLuna/Create-Flavored#61]
The following Casing block items are not properly tagged as `create:casing`:
- `create_dd:tin_casing`
- `create_dd:netherite_casing`
- `create_dd:brick_casing`
- `create_dd:nether_brick_casing`
- `create_dd:mossy_andesite_casing`
- `create_dd:overcharged_casing`
- `create_dd:blaze_gold_casing`
- `create_dd:stargaze_singularity_casing`

It seems like these Casing blocks are tagged for blocks, but not for items.

**Comment by LopyLuna** [comment]
Mod currently getting a rewrite and the following content that you listed will be removed from the main mod
