### ISSUE TITLE
Attribute filter for bulk super heat and bulk freezing

### ISSUE THREAD

**Issue by Kethku** [LopyLuna/Create-Flavored#62]
There is no attribute filter for bulk super heating or bulk freezing making automating the seething and freezing sails much more difficult

**Comment by LopyLuna** [comment]
Huh? Elaborate 
Plus I'm not gonna be working any other versions pre-rewrite

**Comment by Kethku** [comment]
Sorry I wasn't specific enough!

I would expect that when using a create attribute filter and using a reference item such as a block of coal which can be processed using the seething sail, you would be able to filter by if the item can be bulk super heated.

![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/3323631/e90b7796-8cf2-49de-9f01-fdd53d1583a5)

Its very possible I'm missing something, but I would expect that an attribute would show up in this list such as super heatable or something like that.

I think this because the vanilla create bulk processing recipes have equivalent recipes. For example, if I use kelp as a reference item, I can filter by if items are smokeable.

![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/3323631/c7b66b0d-ca1e-4d87-b6d9-73709ce632eb)

That said, I didn't know a rewrite was in the works! If thats the case, I may dig in and work on a temp fix to add in the attribute myself for the current version as a stop gap. Love the project <3

**Comment by Kethku** [comment]
Its been a long time since I've dug in to java codebases let alone minecraft modding, so I'm not sure if this is the right direction, but I looked into the create repo and found [ItemAttribute](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/content/logistics/filter/ItemAttribute.java#L134-L155) which has among other things the filters I expected in the base mod.

Weirdly in that same folder is a subfolder which seems to add attribute filters for AstralSorcery which seems weird to include in the create repo itself. Maybe thats a bad sign and attributes cant be extended without an upstream change?

**Comment by LopyLuna** [comment]
should be fixed now i just added tags for them
