### ISSUE TITLE
"Detected setBlock in a far chunk" log spam

### ISSUE THREAD

**Issue by ElRichiRicon** [LopyLuna/Create-Flavored#64]
[latest.log](https://pastebin.com/tgHBcb0n)

`[01Jun2024 15:10:00.312] [Worker-Main-10/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [63, 127], pos: MutableBlockPos{x=1022, y=-14, z=2032}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / create_dd:striated_ores_savanna]` or  similar

It starts at 
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/45831667/e99916b9-8cd7-4a66-a658-b355a28a73ae)
and ends at
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/45831667/235d9523-a10c-4f41-9687-083e64a3cb30)
so about 340 000 errors.

Happens when creating a world or teleporting very far

**Comment by ascenstohe4vn** [comment]
https://modrinth.com/mod/dsbg

**Comment by LopyLuna** [comment]
vanilla minecraft issue
