### ISSUE TITLE
IllegalStateException ExceptionInInitializerError if Create: Aquatic Ambitions also loaded

### ISSUE THREAD

**Issue by Klisz** [LopyLuna/Create-Flavored#73]
An IllegalStateException occurs during DesireFanProccessingTypes on startup in 0.1a-Release-Early-Dev on Forge 1.20.1 if Create: Aquatic Ambitions is also enabled.

[Crash log with only DnD, Aquatic Ambitions, and Create itself enabled.](https://mclo.gs/a3iw3VZ)

**Comment by LopyLuna** [comment]
issue been fixed
