### ISSUE TITLE
Shapeless crafting of lapis alloy

### ISSUE THREAD

**Issue by Jan-DT** [LopyLuna/Create-Flavored#74]
The andesite alloy in Create allows shapeless crafting using a mixer. This kinda makes sense, as it seems logical that creating an alloy of two materials requires mixing the materials together.
Would this maybe be an idea for the Lapis Alloy as well? Right now it seems to only allow shaped crafting using the mechanical crafter.
I noticed the andesite alloy in create only requires 1 andesite and 1 nugget for mixing, but it might be better to require two for lapis alloy, as it would maybe get a bit too cheap otherwise, but it would certainly make automation a bit easier.

**Comment by LopyLuna** [comment]
intended
