### ISSUE TITLE
Incompatible with Zeta apparently

### ISSUE THREAD

**Issue by oliverrook** [LopyLuna/Create-Flavored#77]
I don't normally post stuff like this, but I have been getting this issue, even if I can't find it in the crash log, and there's an issue on Zeta stating that it's this mod that's crashing it. So I don't exactly know what's going on, but the mod author's should probably discuss this:

https://github.com/VazkiiMods/Zeta/issues/23#issuecomment-2191817973

**Comment by LopyLuna** [comment]
it's nothing related to Zeta but this issue been fixed now

**Comment by quat1024** [comment]
Probably is partially related to zeta - we loop over recipes fairly early (see https://github.com/VazkiiMods/Zeta/blob/main/src/main/java/org/violetmoon/zeta/util/handler/RecipeCrawlHandler.java ), which tends to exercise people's `getCraftingResultItem`/etc functions pretty well 😛

**Comment by LopyLuna** [comment]
well its fixed either way
