### ISSUE TITLE
1.18.2 Industrial Fan Splashing recipes crashes the game.

### ISSUE THREAD

**Issue by KodYazanDruid** [LopyLuna/Create-Flavored#8]
Crash Log:
[crash-2023-09-28_18.05.02-server.txt](https://github.com/LopyLuna/Create-Dreams-and-Desires/files/12751119/crash-2023-09-28_18.05.02-server.txt)
With sail or blaze burner it crashes.

**Comment by LopyLuna** [comment]
![image](https://github.com/LopyLuna/Create-Dreams-and-Desires/assets/100169742/4a512a21-7060-4c8d-b9e2-24246cefad23)
