### ISSUE TITLE
Various Rubber Tree based issues

### ISSUE THREAD

**Issue by Bentcheesee** [LopyLuna/Create-Flavored#80]
1: Rubber Sapling and Rubber Leaves are missing loot tables
![image](https://github.com/user-attachments/assets/75a37aa2-0c1a-40fc-94db-97ae516401fe)

2: Rubber Logs and Rubber Wood are not strippable with an axe in-world (bug portion), nor have stripping recipes with Farmer's Delight Cutting Board (not bug portion).

3: Rubber Logs generate less Sap than Acacia Logs in Item Draining recipes, which ideally, Rubber Logs would generate more Sap and would be more efficient for Rubber production (QoL/Logistics).

**Comment by LopyLuna** [comment]
outdated

**Comment by Bentcheesee** [comment]
This is the latest version, and the screenshot is pulled directly from mod assets.

Do you mean fixed in the next version?

**Comment by LopyLuna** [comment]
mod version is outdated

**Comment by Bentcheesee** [comment]
![image](https://github.com/user-attachments/assets/07f6952e-5cf7-46d3-936b-97ccb01c22bd)

**Comment by LopyLuna** [comment]
thats not the newest version huh?
id suggest updating forge and see if that helps

**Comment by Bentcheesee** [comment]
The latest update for 1.18.2 is at December 4th, 2023 on both Modrinth and CurseForge
![image](https://github.com/user-attachments/assets/17f09730-093f-4848-837f-6bf8caf4d183)
![image](https://github.com/user-attachments/assets/d63ebdd9-83b3-4d36-8434-35d691f29282)

Is 1.18.2 no longer receiving support?  If so, bummer...

**Comment by LopyLuna** [comment]
oh i thought you mentioned 1.19
yeah 1.18 is no longer supported

**Comment by Bentcheesee** [comment]
damn, I shall datapack it myself then
