### ISSUE TITLE
Blaze cake doesn't make blaze burners overheated

### ISSUE THREAD

**Issue by TeslaReloaded** [LopyLuna/Create-Flavored#83]
While this mod is active the blaze cake doesn't cause the blaze burner to become overheated, instead acting like regular fuel.
Mod version: Create-DnDesire-1.20.1-0.1b.Release-Early-Dev.jar (for Forge).

**Comment by nebulazorua** [comment]
Also have this issue. Seems related to adding ablaze rods to the special fuels before the tag is ready
![image](https://github.com/user-attachments/assets/64ac8117-0ff8-4892-8854-92a79114e4a8)

**Comment by LopyLuna** [comment]
install Load my F***ing Tags will fix the issue currently
it will be fixed next update its a known issue
