### ISSUE TITLE
Sap is unattainable, Sails uncraftable 

### ISSUE THREAD

**Issue by Swoofterkitty** [LopyLuna/Create-Flavored#84]
Hello!

I am using Create: Dreams & Desires 1.20.1 0.1b.Release-Early-Dev, and running it on a server
One of the recent updates removed the recipe for getting sap from stripped logs, and because of it all of the sails are uncraftable.

**Comment by LopyLuna** [comment]
dupe issue & fixed in next update

**Comment by wolff000** [comment]
I am running the latest version on 1.20.1 and sap still seems unattainable. Is this corrected yet?
