### ISSUE TITLE
Concurrent Modification Exception on server launch

### ISSUE THREAD

**Issue by MaxWasUnavailable** [LopyLuna/Create-Flavored#87]
MC: 1.20.1
Forge: 47.3.4
Create: 0.5.1.f
Create DnD: 0.1b

Error: https://pastebin.com/W9Eiv1qN

**Comment by LopyLuna** [comment]
the error actually doesn't provide anything good
things I suggest installing that might fix it but idk is Load my F***ing Tags & install kubjs to remove the Additional Drop Tool tag from the gilded rose tools
