### ISSUE TITLE
HOW TO GET FUFING SEETHING BLASES

### ISSUE THREAD

**Issue by sena5641** [LopyLuna/Create-Flavored#91]
Please add some in game clues.
I had to figure out which of my 360 mods forbids me from feeding cakes to blazes and I had to check the mod code to check which mod does it..
and I still don't know how to get seething blaze

**Comment by LopyLuna** [comment]
id suggest installing "Load my F***ing Tags" mod

if you are talking about then entity you bulk seethe the blaze

**Comment by LopyLuna** [comment]
will be fixed next update

**Comment by sena5641** [comment]
I don't think you understood what I mean. 
I'll try to explain it better.

The problem is that your mod prohibits seethe blaze burners using blaze cakes. But it leaves no clues as to what is needed for this or how to get seething blaze sticks. And in create there is a pounder that blaze cake is the only way to get a seething blaze burner.

you can fix this either by adding a guide book or by adding some kind of hint in jei or adding how to get seething blaze to website of your mod.

**Comment by LopyLuna** [comment]
gotta elaborate it more
bc it sounds like you can't use blaze cakes on blaze burners which is a bug 
like I said install Load my F***ing Tags mod

**Comment by ambientNexus** [comment]
> gotta elaborate it more bc it sounds like you can't use blaze cakes on blaze burners which is a bug like I said install Load my F***ing Tags mod

They're saying that the presumed way to get a seething blaze entity, right-clicking a blaze with a blaze cake, is not how you actually do it. Due to the lack of documentation, there's no indication that you have to get a blaze infront of a seething fan.

**Comment by LopyLuna** [comment]
yeah will also be fixed in next update
